#!/usr/bin/env python3
"""
CMDB Syncer CLI Interface
"""
import os, sys
if 'config' not in os.environ:
    os.environ['config'] = 'prod'

try:
    from application import app
except Exception as exp:
    print("Cannot Load Application. Is the Virtual Environment loaded?")
    print(exp)
    sys.exit(1)

if __name__ == '__main__':
    app.cli()
