#!/usr/bin/env python3
"""
CMDB Syncer CLI Interface
"""
import os
if 'config' not in os.environ:
    os.environ['config'] = 'prod'

from application import app
if __name__ == '__main__':
    app.cli()
