#!/bin/bash
# Simple Helper
# .local.
CONTAINER=cmdb_syncer
APPLICATION=cmdb_syncer-api-1

case "$1" in
"dcup")
    docker-compose -f docker-compose.yml -f docker-compose.local.yml build
    docker-compose -f docker-compose.yml -f docker-compose.local.yml -p $CONTAINER up --force-recreate -d
    ;;
"dcstart")
    docker-compose -f docker-compose.yml -f docker-compose.local.yml -p $CONTAINER start
    ;;
"dcstop")
    docker-compose -f docker-compose.yml -f docker-compose.local.yml -p $CONTAINER stop
    ;;
"dcdown")
    docker-compose -f docker-compose.yml -f docker-compose.local.yml -p $CONTAINER down --rmi local --remove-orphans
    ;;
"dclogs")
    echo "Start Container Logs"
    docker logs -f $APPLICATION
    ;;
"dcshell")
    echo "Start Container Shell"
    docker exec -it $APPLICATION
    ;;
"bve")
    python3 -m venv ENV
    ;;
*)
    echo "Simple Helper for CMDB Syncer Jobs."
    echo "For Docker Compose: dcup, dcdown, dcstart, dcstop, dclogs and dcshell are the options"
    echo "Create a venv with bve"
    ;;
esac
