site_name: Cmdbsyncer Documentation
nav:
  - Home: index.md
  - "First Steps":
      - General:
        - How it Works: basics/how_it_works.md
      - Setup:
        - Installation from Code: basics/setup_code.md
        - Installation with Docker: basics/setup_docker.md
        - Updates: basics/updates.md
        - First Steps: basics/first_steps.md
        - Config: basics/lcl_config.md
        - Caching: basics/caching.md
        - Accounts: basics/accounts.md
        - Cronjobs: basics/cron.md
        - Fileadmin: basics/fileadmin.md
        - Recipes:
            - UWSGI and Apache: basics/uwsgi_apache.md
            - Debug Requests: basics/debug.md
            - Change GUI Colors: basics/config_colors.md
      - Principles:
        - Import Systems: basics/import.md
        - Export Systems: basics/export.md
        - Remove Hosts: basics/maintenance.md
        - Hosts, Labels and Inventory: basics/host_labels_inventory.md
        - Conditions: basics/conditions.md
        - Custom Attributes: basics/custom_attributes.md
        - Rewrite Attributes: basics/rewrite_attributes.md
        - Rewrite Hostnames: basics/rewrite_hostnames.md
        - Filter: basics/filter.md
        - Debug Rules: basics/debug_rules.md
      - Updates:
        - Update to 3.5: updates/3-5.md


  - "Modules":
      - Ansible: 
        - Basics: ansible/index.md
        - Recipes:
          - Checkmk Agents: ansible/cmk_agents.md
          - Checkmk Sites: ansible/cmk_sites.md
      - CSV: csv/index.md
      - Checkmk:
          - Main: checkmk/index.md
          - Commandline: checkmk/commandline.md
          - Export Rules: checkmk/export_rules.md
          - Groups Management: checkmk/groups_management.md
          - Rules Management: checkmk/rules_management.md
          - Hosttag Management: checkmk/create_hosttags.md
          - Folder Pools: checkmk/folder_pools.md
          - Recipes Checkmk:
              - Custom Attributes: checkmk/cmk_attributes.md
              - Create Cluster: checkmk/create_cluster.md
              - Manage Contact Groups: checkmk/recipe_contact_groups.md
              - Create Rules: checkmk/recipe_checkmk_rules.md
              - Create Multiple HTTP Rules: checkmk/recipe_multiple_http_rules.md
              - Full Agenten Automations: ansible/cmk_agents.md
              - Site Update Automations: ansible/cmk_sites.md
      - Cisco Dna: ciscodna/index.md
      - Netbox: netbox/index.md
      - RestApi: restapi/index.md
      - SYS: sys/index.md
  - "Advanced":
     - Build your own Plugin: advanced/own_plugins.md
     - Plugin API: advanced/plugin_api.md
     - Background Jobs: advanced/background_jobs.md

theme: readthedocs

plugins:
- search
- mkdocstrings
