---
- name: "Register Agent for TLS."
  become: true
  ansible.builtin.shell: |
    cmk-agent-ctl register -H {{ inventory_hostname }} \
    -s {{ cmk_server }}:{{ cmk_agent_receiver_port }}  -i {{ cmk_site }} \
    -U {{ cmk_user }} --password {{ cmk_secret }} --trust-cert
  when: cmk_register_tls | bool
  ignore_errors: yes

- name: "Register Agent on Local Bakery."
  become: true
  ansible.builtin.shell: |
    cmk-update-agent register -H {{ inventory_hostname }} \
    -s {{ cmk_server }} -i {{ cmk_site }} -p https \
    -U {{ cmk_user }} --password {{ cmk_secret }}
  when: cmk_register_bakery | bool
  ignore_errors: yes

- name: "Register Agent on Central Bakery."
  become: true
  ansible.builtin.shell: |
    cmk-update-agent register -H {{ inventory_hostname }} \
    -s {{ cmk_main_server }} -i {{ cmk_main_site }} -p https \
    -U {{ cmk_user }} --password {{ cmk_secret }}
  when: cmk_register_central_bakery | bool
  ignore_errors: yes

- name: "Cleanup cache"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/check_mk_agent/cache/plugins_3600\cmk-update-agent.cache
    - /var/lib/check_mk_agent/cache/plugins_cmk-update-agent.cache
  when: cmk_register_central_bakery or cmk_register_bakery
  ignore_errors: yes
