#!/bin/bash
#START SETTINGS
API="https://vlcmkop010.at.inside/hostapi/api/v1/ansible"
SECRET="TEST123"
#END SETTINGS
case "$1" in
"--list")
    curl -X 'GET' $API/ \
         -H 'accept: application/json' \
         -H "x-login-token: $SECRET" \
         2> /dev/null
    ;;
"--host")
    curl -X 'GET' ${API}/{$2} \
         -H 'accept: application/json' \
         -H "x-login-token: $SECRET" \
         2> /dev/null
    ;;
*)
    echo "This is a Ansible Inventory Source"
    echo "Please configure API and SECRET"
    ;;
esac

