#!/bin/sh
# Backward-compatible shim: thin proxy to the new
# `cmdbsyncer ansible inventory cmk_sites` CLI command.
# Used by `cmk_server_mngmt.yml` for the Checkmk Sites catalogue.
exec ../cmdbsyncer ansible inventory cmk_sites "$@"
