#!/bin/sh
LIMIT_VALUE=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --limit)
      LIMIT_VALUE="$2"
      shift 2
      ;;
    --limit=*)
      LIMIT_VALUE="${1#--limit=}"
      shift
      ;;
    *)
      shift
      ;;
  esac
done


if [ -n "$LIMIT_VALUE" ]; then
    vars=$(docker exec -it cmdb_syncer-api-1 /srv/cmdbsyncer ansible source --host $LIMIT_VALUE |jq )
cat<<EOF
{"_meta":{"hostvars": {"$LIMIT_VALUE": $vars }}, "all": {"hosts": ["$LIMIT_VALUE"]}}
EOF
else
    docker exec -it cmdb_syncer-api-1 /srv/cmdbsyncer ansible source $1 $2
fi

