#!/bin/sh

#!/bin/sh
LIMIT_VALUE=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --limit)
      LIMIT_VALUE="$2"
      shift 2
      ;;
    --limit=*)
      LIMIT_VALUE="${1#--limit=}"
      shift
      ;;
    *)
      shift
      ;;
  esac
done


if [ -n "$LIMIT_VALUE" ]; then
    vars=$(../cmdbsyncer ansible source --host $LIMIT_VALUE 2>/dev/null)
cat<<EOF
{"_meta":{"hostvars": {"$LIMIT_VALUE": $vars }}, "all": {"hosts": ["$LIMIT_VALUE"]}}
EOF
else
    ../cmdbsyncer ansible source $1 $2 2>/dev/null
fi
